config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  post 'basket/set_book' => 'basket#set_book', as: 'set_book'
  delete 'reset_basket' => 'basket#reset_basket'
  delete 'delete_basket_book/:id(.:format)', as: "delete_basket_book",
         to: 'basket#delete_basket_book'
  get 'basket/change_flat' => 'basket#change_flat', as: 'change_flat'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket
  def self.change_flag(session)
    solve = ''
    if session[:flag] == 'EUR'
      solve ='WORLD'
    end
    if session[:flag] == 'WORLD'
      solve ='EUR'
    end
    solve
  end
  def self.bought_books(session)
    # solve (array of arrays):
    # [
    # tuple1-> [id_book1, quantity , base price, tax, price with IVA to pay],
    # tuple2-> [id_book2, cantidad , El precio base de la compra, Los impuestos a pagar por la compra, El precio con IVA a pagar por la compra],
    # ...
    # ]
    solve = Array.new
    session_basket = session[:basket]
    session_flag = session[:flag]
    basket_clean = session_basket.uniq # ids not repeated

    if session_basket.count > 0
      basket_clean.each do |id_book|
        book = Book.find(id_book)

        tuple = Array.new
        tuple << id_book

        quantity = session_basket.count(id_book)
        tuple << quantity

        base_price = book.base_price(quantity)
        tuple << base_price.round(2)

        tax = book.tax(session_flag, base_price)
        tuple << tax.round(2)

        price_with_tax = base_price + tax
        tuple << price_with_tax.round(2)

        solve << tuple
      end
    end
    solve
  end
  def self.total_bought_books(bought_books)
    base_price = 0
    tax = 0
    base_price_with_tax = 0
    solve = Array.new
    bought_books.each do |book|
      base_price += book[2]
      tax += book[3]
      base_price_with_tax += book[4]
    end
    solve << base_price
    solve << tax
    solve << base_price_with_tax
    solve
  end
end

app/models/book.rb
class Book < ApplicationRecord
  def with_tax?
    kind_price ? 'with tax':'base'
  end

  def base_price(quantity)
    if kind_price
      vats = YAML.load_file("#{Rails.root}/config/vats.yml")
      vat_book = vats[country]
      price_vat = price - (price * vat_book)
      price_vat * (1-(discount/100)) * quantity
    else
      price * (1-(discount/100)) * quantity
    end
  end

  def tax(flag, base_price)
    vats = YAML.load_file("#{Rails.root}/config/vats.yml")
    vat_book = vats[country]
    if flag == 'EUR'
      if kind_price
        base_price - (base_price / (1 + vat_book))
      else
        base_price * vat_book
      end
    elsif flag == 'WORLD'
      0
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :init_site

  def init_site
    session[:basket] ||= Array.new
    session[:flag] ||= 'EUR'
    @flag = session[:flag]
    @basket = session[:basket].count
    @buyed = Basket.bought_books(session)
    @buyed_total = Basket.total_bought_books(@buyed)
  end
end

app/controllers/basket_controller.rb
class BasketController < ApplicationController
  def set_book
    @book = Book.find(params[:id])
    session[:basket] << params[:id]
    redirect_to '/'
  end

  def reset_basket
    session[:basket] = Array.new
    redirect_to '/'
  end

  def delete_basket_book
    @book=Book.find(params[:id])
    # delete first params[:id] in session[:basket]
    session[:basket].delete_at(session[:basket].find_index(@book.id.to_s))
    redirect_to '/'
  end

  def change_flat
    session[:flag] = Basket.change_flag(session)
    redirect_to '/'
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<div class="row">
    <% @books.each do |book| %>
    <div class="col-3">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="<%= book.image %>" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title"><%= book.name %></h5>
          <span class="card-text">Readed: <%= book.readed %> </span> <br/>
          <span class="card-text">Country: <%= book.country %> </span> <br/>
          <span class="card-text">Discount: <%= book.discount %> </span> <br/>
          <%= form_for(book, url: url_for(controller: 'basket', action: 'set_book',                                           params: {id: book.id}), remote: true, method: 'post') do |f| %>
            <%= button_tag(type: 'submit', class: "btn btn-primary", id: "button_add-#{book.id}") do %>
              <i class="fa fa-cart-plus"></i> Comprar
            <% end %>
            <b><%= book.price %> €</b> (<%= book.with_tax? %>)
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
</div>

app/views/layouts/_basket.html.erb
<div class="modal fade basket" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <% if @buyed.present?%>
        <table class="table table-bordered">
          <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Quantity</th>
            <th scope="col">Base Price</th>
            <th scope="col">Tax</th>
            <th scope="col">Price with Tax</th>
          </tr>
          </thead>
          <tbody>
          <% @buyed.each do |book|%>
            <tr>
              <th ><%= Book.find(book[0]).name %></th>
              <td><%= book[1] %></td>
              <td><%= book[2] %></td>
              <td><%= book[3] %></td>
              <td><%= book[4] %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <br/>
        <h3>Total to pay</h3>
        <table class="table table-bordered">
          <thead>
          <tr>
            <th scope="col">Base Price</th>
            <th scope="col">Tax</th>
            <th scope="col">Base Price with Tax</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td><%= @buyed_total[0] %></td>
            <td><%= @buyed_total[1] %></td>
            <td><%= @buyed_total[2] %></td>
          </tr>
          </tbody>
        </table>
        <% else %>
        <span>Carrito vacio</span>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light navbar-fixed-top">
  <a class="navbar-brand" href="#">BOOKS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
    <div class="my-2 my-lg-0">
      <%= link_to change_flat_path, method: :get, class: 'btn btn-warning' do %>
        <span class="fa fa-flag fa-2x"></span> <span id="flag"><%=@flag%></span>
      <% end %>

      <%= link_to reset_basket_path, method: :delete, data: { confirm: '¿Seguro de eliminar carro?' }, class: 'btn btn-danger' do %>
        <span class="fa fa-trash fa-2x"></span>
      <% end %>

      <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".basket">
        <%=fa_icon 'cart-arrow-down 2x'%> <span id="basket"><%=@basket%></span>
      </button>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books24S</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= render 'layouts/basket'%>
    <% if notice.present? %>
    <div class="alert alert-success alert-dismissable">
      <i class="fa fa-thumbs-o-up"></i>
      <strong><%= t('common.info') %></strong>
      <%= notice.html_safe %>
      <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
    </div>
  <% end %>
  <% if alert.present? %>
    <div class="alert alert-danger alert-dismissable">
      <i class="fa fa-warning"></i>
      <strong><%= t('common.danger') %></strong>
      <%= alert.html_safe %>
      <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
    </div>
  <% end %>
    <br/><br/><br/><br/>
    <%= yield %>
  </body>
</html>